
services:
  db:
    image: postgres:15-alpine
    container_name: strava_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  ingestion:
    build: ./ingestion
    container_name: strava_ingestion
    depends_on:
      - db
    env_file:
      - .env

  dashboard:
    build: ./dashboard
    container_name: strava_dashboard
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8501:8501"

volumes:
  pgdata: